---
- name: Setup
  hosts: manager, agent
  become: true
  gather_facts: false # Skip gathering facts for this play
  tags: "1"

  tasks:
    - name: Update system
      apt:
        update_cache: yes
        upgrade: yes

    - name: Set timezone to Europe/Stockholm
      timezone:
        name: Europe/Stockholm

- name: Configure netplan on manager
  hosts: manager
  become: true
  gather_facts: false # Skip gathering facts for this play
  tags: "2"
  tasks:
    - name: Configure netplan
      template:
        src: netplan-config.j2
        dest: /etc/netplan/50-cloud-init.yaml

    - name: Apply netplan configuration
      command: netplan apply

- name: Configure netplan on agent
  hosts: agent
  become: true
  gather_facts: false # Skip gathering facts for this play
  tags: "3"
  tasks:
    - name: Configure netplan
      template:
        src: netplan-config.j2
        dest: /etc/netplan/50-cloud-init.yaml

    - name: Apply netplan configuration
      command: netplan apply

- name: Install and configure manager
  hosts: manager
  become: true
  gather_facts: false # Skip gathering facts for this play
  tags: "4"
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - snmp
          - snmp-mibs-downloader
          - libsnmp-dev
        state: present

    - name: Comment out 'mibs :' in snmp.conf if not already commented
      shell: sed -i '/^mibs :/ {/^[#]/! s/^/#/}' /etc/snmp/snmp.conf
    #TODO

- name: Install and configure agent
  hosts: agent
  become: true
  gather_facts: false # Skip gathering facts for this play
  tags: "5"
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - snmpd
          - libsnmp-dev
        state: present

    - name: Edit agentaddress in /etc/snmp/snmpd.conf
      shell: sed -i '/^agentaddress/c\agentaddress udp:161' /etc/snmp/snmpd.conf
    #TODO

    - name: Insert communities in /etc/snmp/snmpd.conf
      shell: |
        sed -i '/^#   arguments:  c/a\
        rocommunity public 172.20.0.0/24\
        rocommunity public localhost\
        rwcommunity private 172.20.0.0/24\
        rwcommunity private localhost\
        ' /etc/snmp/snmpd.conf
    #TODO
    - name: Comment out sysLocation and sysContact in /etc/snmp/snmpd.conf
      shell: sed -i '/^sysLocation\|^sysContact/s/^/#/' /etc/snmp/snmpd.conf
    #TODO

    - name: Restart snmpd service
      systemd:
        name: snmpd
        state: restarted

- name: GET sysName
  hosts: manager
  become: false
  gather_facts: false # Skip gathering facts for this play
  tags: "6"
  tasks:
    - name: Get sysName from agent using snmpget
      command: snmpget -v2c -c public {{ hostvars['agent']['ansible_host'] }} SNMPv2-MIB::sysName.0
      register: snmp_result

    - name: Display sysName
      debug:
        msg: "The sysName is: {{ snmp_result.stdout }}"

- name: Count MIBs
  hosts: manager
  become: false
  gather_facts: false # Skip gathering facts for this play
  tags: "7"
  tasks:
    - name: Get number of mibs in root using snmpwalk
      shell: snmpwalk -v2c -c public {{ hostvars['agent']['ansible_host'] }} . | wc -l
      register: number_of_mibs

    - name: Display number of MIBs
      debug:
        msg: "The number of MIBs in root is: {{ number_of_mibs.stdout }}"

- name: SET sysContact and sysLocation
  hosts: manager
  become: false
  gather_facts: false # Skip gathering facts for this play
  tags: "8"
  tasks:
    - name: Set sysContact on agent using snmpset
      shell: snmpset -v2c -c private {{ hostvars['agent']['ansible_host'] }} SNMPv2-MIB::sysContact.0 s "sysContact set by Ansible"

    - name: Set sysLocation on agent using snmpset
      shell: snmpset -v2c -c private {{ hostvars['agent']['ansible_host'] }} SNMPv2-MIB::sysLocation.0 s "sysLocation set by Ansible"

- name: GET sysContact and sysLocation
  hosts: manager
  become: false
  gather_facts: false # Skip gathering facts for this play
  tags: "9"
  tasks:
    - name: Get sysContact from agent using snmpget
      shell: snmpget -v2c -c public {{ hostvars['agent']['ansible_host'] }} SNMPv2-MIB::sysContact.0
      register: sysContact_result

    - name: Get sysLocation from agent using snmpget
      shell: snmpget -v2c -c public {{ hostvars['agent']['ansible_host'] }} SNMPv2-MIB::sysLocation.0
      register: sysLocation_result

    - name: Display sysContact
      debug:
        msg: "The sysContact is: {{ sysContact_result.stdout }}"

    - name: Display sysLocation
      debug:
        msg: "The sysLocation is: {{ sysLocation_result.stdout }}"

- name: WALK tcpConnLocalPort and udpLocalPort
  hosts: manager
  become: false
  gather_facts: false # Skip gathering facts for this play
  tags: "10"
  tasks:
    - name: Walk tcpConnLocalPort using snmpwalk
      shell: snmpwalk -v2c -c public {{ hostvars['agent']['ansible_host'] }} tcpConnLocalPort
      register: tcpConnLocalPort_result

    - name: Walk udpLocalPort using snmpwalk
      shell: snmpwalk -v2c -c public {{ hostvars['agent']['ansible_host'] }} udpLocalPort
      register: udpLocalPort_result

    - name: Display tcpConnLocalPort
      debug:
        msg: "The tcpConnLocalPort is: {{ tcpConnLocalPort_result.stdout }}"

    - name: Display udpLocalPort
      debug:
        msg: "The udpLocalPort is: {{ udpLocalPort_result.stdout }}"

- name: GET sysName
  hosts: manager
  become: false
  gather_facts: false # Skip gathering facts for this play
  tags: "11"
  tasks:
    - name: Get sysName from sw_center using snmpget
      command: snmpget -v2c -c public {{ hostvars['sw_center']['ansible_host'] }} SNMPv2-MIB::sysName.0
      register: sysName_result

    - name: Get sysDescr from sw_center using snmpget
      command: snmpget -v2c -c public {{ hostvars['sw_center']['ansible_host'] }} SNMPv2-MIB::sysDescr.0
      register: sysDescr_result

    - name: Display sysName
      debug:
        msg: "The sysName is: {{ sysName_result.stdout }}"

    - name: Display sysDescr
      debug:
        msg: "The sysDescr is: {{ sysDescr_result.stdout }}"

- name: Configure SNMPv3 user
  hosts: agent
  become: true
  gather_facts: false
  tags: "12"
  tasks:
    - name: Stop SNMP daemon
      systemd:
        name: snmpd
        state: stopped

    - name: Create SNMPv3 user
      command: net-snmp-create-v3-user -A 5Eptember! -X 5Eptember! -a MD5 -x DES snmpv3user

    - name: Configure SNMPD to add rwuser after rouser authPrivUser
      shell: sed -i '/^rouser authPrivUser/a rwuser snmpv3user' /etc/snmp/snmpd.conf
    #TODO
    - name: Start SNMP daemon
      systemd:
        name: snmpd
        state: started

- name: Verify SNMPv3 user from manager
  hosts: manager
  become: false
  gather_facts: false
  tags: "13"
  tasks:
    - name: Verify SNMPv3 user
      command: snmpwalk -v3 -u snmpv3user -l authPriv -a MD5 -A 5Eptember! -x DES -X 5Eptember! 172.20.0.27 sysName
      register: snmpwalk_output

    - name: Display SNMPv3 user verification
      debug:
        msg: "{{ snmpwalk_output.stdout }}"

- name: Configure SNMP settings for user
  hosts: manager
  become: true
  gather_facts: false
  tags: "14"
  tasks:
    - name: Display the user running the playbook
      debug:
        msg: "The playbook is being run by user: {{ ansible_user }}"

    - name: Create SNMP configuration file and insert settings
      shell: |
        mkdir -p ~/.snmp && \
        echo "defSecurityName snmpv3user\n\
        defVersion 3\n\
        defAuthType MD5\n\
        defPrivType DES\n\
        defAuthPassphrase 5Eptember!\n\
        defPrivPassphrase 5Eptember!\n\
        defSecurityLevel authPriv" > ~/.snmp/snmp.conf
    #TODO
    - name: Verify SNMPv3 user
      command: snmpset {{ hostvars['agent']['ansible_host'] }} sysName.0 s "sysName set by Ansible"
      # snmpwalk -v3 -u snmpv3user -l authPriv -a MD5 -A 5Eptember! -x DES -X 5Eptember! {{ hostvars['agent']['ansible_host'] }} sysName
      register: snmpwalk_output

    - name: Display SNMPv3 user verification
      debug:
        msg: "{{ snmpwalk_output.stdout }}"

- name: Install packages agent
  hosts: agent
  become: true
  gather_facts: false # Skip gathering facts for this play
  tags: "15"
  tasks:
    - name: Install packages
      apt:
        name:
          - snmp
          - snmp-mibs-downloader
          - snmptrapd
        state: present

    - name: Comment out 'mibs :' in snmp.conf if not already commented
      shell: sed -i '/^mibs :/ {/^[#]/! s/^/#/}' /etc/snmp/snmp.conf
#TODO

- name: Install packages manager
  hosts: manager
  become: true
  gather_facts: false # Skip gathering facts for this play
  tags: "16"
  tasks:
    - name: Install packages
      apt:
        name:
          - snmptrapd
        state: present

    - name: Stop snmptrapd daemon
      systemd:
        name: snmptrapd
        state: stopped

    - name: Insert communities in /etc/snmp/snmptrapd.conf
      shell: |
        sed -i '/^#traphandle ./a\
        createUser snmpv3user MD5 "5Eptember!" DES "5Eptember!"\
        authUser log,execute,net snmpv3user authPriv\
        [snmp] logOption s u' /etc/snmp/snmptrapd.conf
    #TODO "#traphandle ."
    - name: Insert communities in /etc/default/snmptrapd
      shell: |
        sed -i '/^#traphandle ./a\
        TRAPDRUN=yes' /etc/default/snmptrapd
    #TODO #"TRAPDOPTS="
    - name: Start snmptrapd and snmp daemon
      command: systemctl start snmptrapd snmpd

- name: send inform
  hosts: agent
  become: true
  gather_facts: false
  tags: "17"
  tasks:
    - name: Send inform
      shell: snmpinform -v 3 -u snmpv3user -a MD5 -A 5Eptember! -x DES -X 5Eptember! -l authPriv {{ hostvars['manager']['ansible_host'] }} 42 coldStart.0

- name: view inform
  hosts: manager
  become: false
  gather_facts: false
  tags: "18"
  tasks:
    - name: View inform
      command: journalctl -u snmptrapd -n 1
      register: view_inform

    - name: Display inform
      debug:
        msg: "{{ view_inform.stdout }}"
